name: image_picker_windows
publish_to: none
description: Windows platform implementation of image_picker
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.2.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    implements: image_picker
    platforms:
      windows:
        dartPluginClass: ImagePickerWindows

dependencies:
  file_selector_platform_interface: 
    git: https://github.com/kumsumit/file_selector_platform_interface.git
  file_selector_windows: 
    git: https://github.com/kumsumit/file_selector_windows.git
  flutter:
    sdk: flutter
  image_picker_platform_interface: 
    git: https://github.com/kumsumit/image_picker_platform_interface.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - image-picker
  - files
  - file-selection
